apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-demo
  template:
    metadata:
      labels:
        app: nodejs-demo
    spec:
      containers:
      - name: nodejs-demo
        image: maheshbharmbe45/node_img:latest
        ports:
        - containerPort: 3000
